name: Sync Fork

on:
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Fork with Upstream
        uses: tgymnich/fork-sync@v1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: alex4528
          repo: m3u
          base: main
          head: main
          force: true
